import sqlite3
import os
conn=sqlite3.connect("data/badminton.db")
conn.execute("PRAGMA foreign_keys=ON")
conn.executescript("""
CREATE TABLE IF NOT EXISTS Players (
    PlayerID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(50) NOT NULL
);
    
CREATE TABLE IF NOT EXISTS Matches(
    MatchID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayerOneID INTEGER NOT NULL,
    PlayerTwoID INTEGER NOT NULL,
    WinnerID INTEGER NULL,
    FOREIGN KEY(PlayerOneID) REFERENCES Players(PlayerID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(PlayerTwoID) REFERENCES Players(PlayerID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(WinnerID) REFERENCES Players(PlayerID) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS Rally (
    RallyID INTEGER PRIMARY KEY AUTOINCREMENT,
    MatchID INTEGER NOT NULL,
    ServerID INTEGER NOT NULL,
    RallyWinnerID INTEGER NULL,
    RallyNum INTEGER NOT NULL,
    FOREIGN KEY (MatchID) REFERENCES Matches(MatchID)  ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (ServerID) REFERENCES Players(PlayerID) ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (RallyWinnerID) REFERENCES Players(PlayerID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ShotType (
    ShotTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
    ShotTypeName VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Shots (
    ShotID INTEGER PRIMARY KEY AUTOINCREMENT,
	RallyID INTEGER NOT NULL,
	PlayerID INTEGER NOT NULL,
	ShotTypeID INTEGER NOT NULL,
	ShotOrder INTEGER NOT NULL,
	DIRECTION VARCHAR(20),
	isFINAL INTEGER DEFAULT 0,
	FOREIGN KEY (RallyID)    REFERENCES Rally(RallyID)       ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (PlayerID)   REFERENCES Players(PlayerID)    ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (ShotTypeID) REFERENCES ShotType(ShotTypeID) ON DELETE RESTRICT ON UPDATE CASCADE
);
""")
conn.commit()
conn.close()
print("DB created successfully")

